server.port=8087

# JPA and Hibernate settings for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# MySQL datasource settings
spring.datasource.url=jdbc:mysql://localhost:3306/leave_module_db
spring.datasource.username=root
spring.datasource.password=password
http://localhost:8087/swagger-ui/index.html
logging.level.com.leave.management.system=INFO
microsoft.graph.api.url=https://graph.microsoft.com/v1.0
